### ISSUE TITLE
Changes in Project Files Not Detected Automatically in GitButler (Stable and Nightly)

### ISSUE THREAD

**Issue by cuervolu** [gitbutlerapp/gitbutler#5407]
### Version

0.5.855

### Operating System

Linux

### Distribution Method

AppImage (Linux)

### Describe the issue

Since recent updates, both the stable (0.13.8) and Nightly (0.5.855) versions of GitButler are failing to detect changes made to project files automatically. I have to manually reload the view each time to see updates. Additionally, the toolbar is missing in the Nightly version, so I am forced to use CTRL + R to refresh. This behavior does not occur in the stable version, but even there, changes are not detected until a manual refresh.

I have provided a quick video example showing the issue, though this problem also occurs with larger file changes.

https://github.com/user-attachments/assets/3eb91e97-cb2b-4564-919a-61af82df3bd5

I have tested different file changes and reloaded multiple times, but the automatic change detection remains unreliable.

### How to reproduce

1. Open GitButler.
2. Make any changes to your project (small or large).
3. Observe that GitButler does not detect the changes automatically.

### Expected behavior

In previous versions, GitButler detected file changes immediately. I believe this should still be the case unless there is a specific reason for the new behavior (which I'd appreciate clarification on). It's inconvenient to reload the page manually for every minor update.

**Comment by Byron** [comment]
Thanks a lot for reporting!

On MacOS, trying 0.13.7, 0.13.8 and nightly 0.5.855 I was unable to reproduce the issue on MacOS. Reeling in @ndom91 who will probably already have an idea what changed between these releases.

**Comment by cuervolu** [comment]
Any updates on this? The error is still present in the latest stable and nightly versions, though it occurs less frequently.

**Comment by ndom91** [comment]
Hey sorry missed this one. 

So I've been using the appimage for months and I've run into this issue with every version as far back as I can remember unfortunately. 

Do your changes always not get picked up? Or does it work for a while but then at some point stop picking up changes? In my case it works like the second example, the file watcher usually works for a bit, but then stops. 

Anyway, we're aware the file watcher could use some more love, we've put up an issue to track it generally here:

**Comment by cuervolu** [comment]
Yes, it happens like the second option. Sometimes, when I make a commit or a pull request, only then does it realize there were other changes.

Anyway, I'll pay closer attention to that issue, although it's true that AppImages are often quite complex, so I'm not surprised this happens.

**Comment by ndom91** [comment]
> Yes, it happens like the second option. Sometimes, when I make a commit or a pull request, only then does it realize there were other changes.
> 
> Anyway, I'll pay closer attention to that issue, although it's true that AppImages are often quite complex, so I'm not surprised this happens.

As a bit of a workaround, I noticed that certain actions in the app cause the file watcher to sort of refresh. For example, if I change default branches it usually picks up any changes (across all applied branches).

**Comment by JulianDeal** [comment]
I have the same problem on Windows right now. I tested it with Mac first, it worked. Then I installed it on Windows. It took a while on both systems to plow through all the error messages when there was active work. But no changes are detected. Not even when changing the base branch, editing files, or anything.

<img width="647" height="704" alt="Image" src="https://github.com/user-attachments/assets/243fd6db-0400-41dd-aa06-ba8d4ceef6b0" />

Tested with both 17.6 and 18.0.

**Comment by Byron** [comment]
Thanks for sharing! Does the repository live on a non-local disk by any chance? I'd love to understand what could be causing this on Windows, as this doesn't trivially reproduce whenever I test for that (on Windows or Linux).

PS: If you are interested in debugging this and are able to run the Rust toolchain, I'd have some commands for testing that just see how/if the file watcher is working.

**Comment by zipproth** [comment]
I've discovered a curious interaction on Windows that seems related to the file watching issues discussed here.

I'm testing with GitButler 0.18.5 in a Windows 11 (23H2) VM with 32 GB, using the standard notepad.exe and Visual Studio Community 2022 (17.14.20).

- When no Visual Studio instance has the repository folder open, changes made with Notepad are detected immediately in GitButler.
- As soon as I open the repository folder in Visual Studio (even without a solution file – just "Open Folder"), GitButler stops detecting any further file changes, even those made with Notepad.
- Simply having the Visual Studio process running is not sufficient; the repository folder must actually be opened in VS.
- Closing the folder in VS restores immediate detection in GitButler.

I tried enabling the Git file system monitor:
```
git config --global core.fsmonitor true
git config --global core.untrackedCache true
```
followed by a reboot – no improvement.

Hypothesis: Visual Studio might register exclusive file change notifications or locks on the directory tree when opening a folder, potentially interfering with GitButler's (or the underlying Git fsmonitor's) ability to receive change events on Windows.

I've reproduced this reliably multiple times. Happy to provide more details (logs, strace equivalents, etc.) if helpful.

Thanks for looking into these watching issues!

**Comment by Byron** [comment]
Thanks so much for sharing, I think that's very helpful!

Fortunately, I have something you could try out which *might* fix this. An alternative theory could be that the system runs out of handles, and the proposed solution reduces the ones that GB needs.

Could you edit `settings.json` in this directory…

<img width="390" height="474" alt="Image" src="https://github.com/user-attachments/assets/d67561c6-e464-4b73-ae7f-38096aefa395" />

…so that it contains the watch_mode feature?

```json
  "featureFlags": {
    "watch_mode": "modern"
  },
```

It's not the default yet, but it could be in future releases.
Fingers crossed this works, and thanks again 🤞.

> followed by a reboot – no improvement.

Does that mean that even closing VSCode and reopening GitButler won't restore the prior operation?

**Comment by zipproth** [comment]
Thanks for the prompt response.

### Steps Taken
While GitButler was closed, I added the flag. For reference, here's the complete settings.json file after the change:
```json
{
  "featureFlags": {
    "watch_mode": "modern"
  },
  "appAnalyticsConfirmed": true
}
```
(Note: Initially, I accidentally made the change while GitButler was running, and it overwrites the file on close, which makes sense. After editing it with GitButler closed, the change was preserved.)

### Test Results
- I opened GitButler (no Visual Studio Community running). Changes made via VS Code were detected with a short delay (< 1 s).
- Then I opened the folder in Visual Studio Community and changed a repo file in VS Code – unfortunately, GitButler did not detect that change despite the setting being active.
- Closing Visual Studio Community (without any other actions) caused GitButler to instantly detect the file change.
- I re-opened Visual Studio Community, changed another file in VS Code (not detected again), and closed GitButler (while VS Code was still open).
- After rebooting (which closed VS Code and Visual Studio Community), I opened GitButler first, without any other software. The file changed before rebooting was detected.

### Clarification on Tools Used and Your Question
To avoid confusion: In my initial report, I tested file changes with notepad.exe, but in this round, I switched to VS Code (Visual Studio Code) for convenience, as it makes viewing repo files easier than notepad.exe's basic interface. The software used for making changes (notepad.exe or VS Code) is irrelevant to the issue – the bug is triggered solely by opening the folder in Visual Studio Community. The mere presence of Visual Studio Community with the folder open prevents detection of changes to tracked files, regardless of how those changes are made.

On your question:
> Does that mean that even closing VSCode and reopening GitButler won't restore the prior operation?

Just to make sure – did you mean "VS Code" or "Visual Studio Community" in your question? The issue is triggered by Visual Studio Community, so I assume the latter. If so, closing Visual Studio Community and reopening GitButler does restore the prior operation, i.e., the file change that was initially not detected now shows up correctly.

### Additional Observation
GitButler does detect changes in the `.vs` directory created by Visual Studio Community inside the opened folder (for the test, I did not .gitignore it). However, changes to other tracked files are not detected while the repo folder is open in Visual Studio Community (I only changed tracked files). I did not test if closing and reopening the folder in Visual Studio Community triggers the difference, but we can assume it does, as the issue does not occur if the directory is not opened in Visual Studio Community at all.

I'm happy to provide further information. I could do a screencast, but I'm not very experienced with it, so there might be pauses while I'm thinking about the next steps for the test :-)

**Comment by Byron** [comment]
Thanks for responding in such detail!

> (Note: Initially, I accidentally made the change while GitButler was running, and it overwrites the file on close, which makes sense. After editing it with GitButler closed, the change was preserved.)

Actually, it should pick up the change instantly and not write a stale copy back. This allows to toggle features with the app responding to it without restarting. If the filewatchers don't work, I suppose that can lead to races.

And I see my mistake now - the VSCode doesn't cause the issue, but Visual Studio Community does.
It's the first time I hear this.

It's good to see that the 'modern' version of the watcher also doesn't work, which probably means that something fundamental doesn't work anymore then.

**Can you open the logs folder and see if there are 'panic's in the `tokio-console` file, or related errors (`ERROR`) in the log for the day?**

Thanks again.

**Comment by zipproth** [comment]
Thanks for the prompt response. I tracked the logs while reproducing the issue (i.e., using GitButler while the directory is open in Visual Studio Community). In the GitButler.*.log file, these two patterns occur repeatedly:
```
2026-01-22T08:44:23.342145Z  INFO handle: crates\gitbutler-watcher\src\handler.rs:41: new event=ProjectFileChange(44510e02-5e5d-4836-a47d-fa498f65e243, .vs\gitdemo\FileContentIndex)
2026-01-22T08:44:23.354065Z  INFO handle:project_files_change: crates\gitbutler-watcher\src\handler.rs:87: new event=ProjectFileChange(44510e02-5e5d-4836-a47d-fa498f65e243, .vs\gitdemo\FileContentIndex) repo=Repository { kind: WorkTree { is_linked: false }, git_dir: "C:\\Users\\zippr\\gitdemo\\.git", workdir: Some("C:\\Users\\zippr\\gitdemo") } workspace=Workspace(📕🏘️:0:gitbutler/workspace[🌳] <> ✓refs/remotes/origin/master on 350e04f) { id: 0, kind: Managed { ref_info: RefInfo { ref_name: FullName("refs/heads/gitbutler/workspace"), worktree: Some(Main) } }, stacks: [Stack(≡📙:8:sz-branch-1 on 350e04f {ec452a13a824aa95161ff7e2552}) { segments: [StackSegment(📙:8:sz-branch-1) { commits: [], commits_on_remote: [], commits_outside: None }], id: ec452a13-a802-4a0a-9516-10f0f07e2552 }], metadata: Some(Workspace { ref_info: RefInfo { created_at: "2023-01-31 14:55:57 +0000", updated_at: None }, stacks: [WorkspaceStack { id: ec452a13-a802-4a0a-9516-10f0f07e2552, branches: [WorkspaceStackBranch { ref_name: "refs/heads/sz-branch-1", archived: false }], workspacecommit_relation: Merged }], target_ref: "refs/remotes/origin/master", target_commit_id: Sha1(350e04fe35433e6d2941dce5a1f53308f87058eb), push_remote: "origin" }), target_ref: Some(TargetRef { ref_name: FullName("refs/remotes/origin/master"), segment_index: NodeIndex(1), commits_ahead: 0 }), extra_target: None } paths=1
2026-01-22T08:44:23.354091Z  INFO handle:project_files_change:worktree_changes: crates\but-core\src\diff\worktree.rs:37: new event=ProjectFileChange(44510e02-5e5d-4836-a47d-fa498f65e243, .vs\gitdemo\FileContentIndex) repo=Repository { kind: WorkTree { is_linked: false }, git_dir: "C:\\Users\\zippr\\gitdemo\\.git", workdir: Some("C:\\Users\\zippr\\gitdemo") } workspace=Workspace(📕🏘️:0:gitbutler/workspace[🌳] <> ✓refs/remotes/origin/master on 350e04f) { id: 0, kind: Managed { ref_info: RefInfo { ref_name: FullName("refs/heads/gitbutler/workspace"), worktree: Some(Main) } }, stacks: [Stack(≡📙:8:sz-branch-1 on 350e04f {ec452a13a824aa95161ff7e2552}) { segments: [StackSegment(📙:8:sz-branch-1) { commits: [], commits_on_remote: [], commits_outside: None }], id: ec452a13-a802-4a0a-9516-10f0f07e2552 }], metadata: Some(Workspace { ref_info: RefInfo { created_at: "2023-01-31 14:55:57 +0000", updated_at: None }, stacks: [WorkspaceStack { id: ec452a13-a802-4a0a-9516-10f0f07e2552, branches: [WorkspaceStackBranch { ref_name: "refs/heads/sz-branch-1", archived: false }], workspacecommit_relation: Merged }], target_ref: "refs/remotes/origin/master", target_commit_id: Sha1(350e04fe35433e6d2941dce5a1f53308f87058eb), push_remote: "origin" }), target_ref: Some(TargetRef { ref_name: FullName("refs/remotes/origin/master"), segment_index: NodeIndex(1), commits_ahead: 0 }), extra_target: None } paths=1
2026-01-22T08:44:23.362943Z ERROR handle:project_files_change:worktree_changes: crates\but-core\src\diff\worktree.rs:37: error=Could not open worktree file for reading event=ProjectFileChange(44510e02-5e5d-4836-a47d-fa498f65e243, .vs\gitdemo\FileContentIndex) repo=Repository { kind: WorkTree { is_linked: false }, git_dir: "C:\\Users\\zippr\\gitdemo\\.git", workdir: Some("C:\\Users\\zippr\\gitdemo") } workspace=Workspace(📕🏘️:0:gitbutler/workspace[🌳] <> ✓refs/remotes/origin/master on 350e04f) { id: 0, kind: Managed { ref_info: RefInfo { ref_name: FullName("refs/heads/gitbutler/workspace"), worktree: Some(Main) } }, stacks: [Stack(≡📙:8:sz-branch-1 on 350e04f {ec452a13a824aa95161ff7e2552}) { segments: [StackSegment(📙:8:sz-branch-1) { commits: [], commits_on_remote: [], commits_outside: None }], id: ec452a13-a802-4a0a-9516-10f0f07e2552 }], metadata: Some(Workspace { ref_info: RefInfo { created_at: "2023-01-31 14:55:57 +0000", updated_at: None }, stacks: [WorkspaceStack { id: ec452a13-a802-4a0a-9516-10f0f07e2552, branches: [WorkspaceStackBranch { ref_name: "refs/heads/sz-branch-1", archived: false }], workspacecommit_relation: Merged }], target_ref: "refs/remotes/origin/master", target_commit_id: Sha1(350e04fe35433e6d2941dce5a1f53308f87058eb), push_remote: "origin" }), target_ref: Some(TargetRef { ref_name: FullName("refs/remotes/origin/master"), segment_index: NodeIndex(1), commits_ahead: 0 }), extra_target: None } paths=1
```

```
2026-01-22T08:50:13.960760Z  INFO changes_in_worktree:worktree_changes: crates\but-core\src\diff\worktree.rs:37: new ctx=Context { git_dir: "C:\\Users\\zippr\\gitdemo\\.git" }
2026-01-22T08:50:13.967522Z ERROR changes_in_worktree:worktree_changes: crates\but-core\src\diff\worktree.rs:37: error=Could not open worktree file for reading ctx=Context { git_dir: "C:\\Users\\zippr\\gitdemo\\.git" }
2026-01-22T08:50:13.967566Z  INFO changes_in_worktree:worktree_changes: crates\but-core\src\diff\worktree.rs:37: close time.busy=6.79ms time.idle=16.3µs ctx=Context { git_dir: "C:\\Users\\zippr\\gitdemo\\.git" }
2026-01-22T08:50:13.967597Z ERROR changes_in_worktree: crates\but-api\src\legacy\diff.rs:34: error=Could not open worktree file for reading ctx=Context { git_dir: "C:\\Users\\zippr\\gitdemo\\.git" }
```

Closing Visual Studio Community triggers further log entries in GitButler, e.g.:
```
2026-01-22T08:54:23.079459Z  INFO handle: crates\gitbutler-watcher\src\handler.rs:41: new event=ProjectFileChange(44510e02-5e5d-4836-a47d-fa498f65e243, .vs\gitdemo\FileContentIndex)
2026-01-22T08:54:23.094856Z  INFO handle:project_files_change: crates\gitbutler-watcher\src\handler.rs:87: new event=ProjectFileChange(44510e02-5e5d-4836-a47d-fa498f65e243, .vs\gitdemo\FileContentIndex) repo=Repository { kind: WorkTree { is_linked: false }, git_dir: "C:\\Users\\zippr\\gitdemo\\.git", workdir: Some("C:\\Users\\zippr\\gitdemo") } workspace=Workspace(📕🏘️:0:gitbutler/workspace[🌳] <> ✓refs/remotes/origin/master on 350e04f) { id: 0, kind: Managed { ref_info: RefInfo { ref_name: FullName("refs/heads/gitbutler/workspace"), worktree: Some(Main) } }, stacks: [Stack(≡📙:8:sz-branch-1 on 350e04f {ec452a13a824aa95161ff7e2552}) { segments: [StackSegment(📙:8:sz-branch-1) { commits: [], commits_on_remote: [], commits_outside: None }], id: ec452a13-a802-4a0a-9516-10f0f07e2552 }], metadata: Some(Workspace { ref_info: RefInfo { created_at: "2023-01-31 14:55:57 +0000", updated_at: None }, stacks: [WorkspaceStack { id: ec452a13-a802-4a0a-9516-10f0f07e2552, branches: [WorkspaceStackBranch { ref_name: "refs/heads/sz-branch-1", archived: false }], workspacecommit_relation: Merged }], target_ref: "refs/remotes/origin/master", target_commit_id: Sha1(350e04fe35433e6d2941dce5a1f53308f87058eb), push_remote: "origin" }), target_ref: Some(TargetRef { ref_name: FullName("refs/remotes/origin/master"), segment_index: NodeIndex(1), commits_ahead: 0 }), extra_target: None } paths=1
2026-01-22T08:54:23.094895Z  INFO handle:project_files_change:worktree_changes: crates\but-core\src\diff\worktree.rs:37: new event=ProjectFileChange(44510e02-5e5d-4836-a47d-fa498f65e243, .vs\gitdemo\FileContentIndex) repo=Repository { kind: WorkTree { is_linked: false }, git_dir: "C:\\Users\\zippr\\gitdemo\\.git", workdir: Some("C:\\Users\\zippr\\gitdemo") } workspace=Workspace(📕🏘️:0:gitbutler/workspace[🌳] <> ✓refs/remotes/origin/master on 350e04f) { id: 0, kind: Managed { ref_info: RefInfo { ref_name: FullName("refs/heads/gitbutler/workspace"), worktree: Some(Main) } }, stacks: [Stack(≡📙:8:sz-branch-1 on 350e04f {ec452a13a824aa95161ff7e2552}) { segments: [StackSegment(📙:8:sz-branch-1) { commits: [], commits_on_remote: [], commits_outside: None }], id: ec452a13-a802-4a0a-9516-10f0f07e2552 }], metadata: Some(Workspace { ref_info: RefInfo { created_at: "2023-01-31 14:55:57 +0000", updated_at: None }, stacks: [WorkspaceStack { id: ec452a13-a802-4a0a-9516-10f0f07e2552, branches: [WorkspaceStackBranch { ref_name: "refs/heads/sz-branch-1", archived: false }], workspacecommit_relation: Merged }], target_ref: "refs/remotes/origin/master", target_commit_id: Sha1(350e04fe35433e6d2941dce5a1f53308f87058eb), push_remote: "origin" }), target_ref: Some(TargetRef { ref_name: FullName("refs/remotes/origin/master"), segment_index: NodeIndex(1), commits_ahead: 0 }), extra_target: None } paths=1
2026-01-22T08:54:23.110769Z ERROR handle:project_files_change:worktree_changes: crates\but-core\src\diff\worktree.rs:37: error=Could not open worktree file for reading event=ProjectFileChange(44510e02-5e5d-4836-a47d-fa498f65e243, .vs\gitdemo\FileContentIndex) repo=Repository { kind: WorkTree { is_linked: false }, git_dir: "C:\\Users\\zippr\\gitdemo\\.git", workdir: Some("C:\\Users\\zippr\\gitdemo") } workspace=Workspace(📕🏘️:0:gitbutler/workspace[🌳] <> ✓refs/remotes/origin/master on 350e04f) { id: 0, kind: Managed { ref_info: RefInfo { ref_name: FullName("refs/heads/gitbutler/workspace"), worktree: Some(Main) } }, stacks: [Stack(≡📙:8:sz-branch-1 on 350e04f {ec452a13a824aa95161ff7e2552}) { segments: [StackSegment(📙:8:sz-branch-1) { commits: [], commits_on_remote: [], commits_outside: None }], id: ec452a13-a802-4a0a-9516-10f0f07e2552 }], metadata: Some(Workspace { ref_info: RefInfo { created_at: "2023-01-31 14:55:57 +0000", updated_at: None }, stacks: [WorkspaceStack { id: ec452a13-a802-4a0a-9516-10f0f07e2552, branches: [WorkspaceStackBranch { ref_name: "refs/heads/sz-branch-1", archived: false }], workspacecommit_relation: Merged }], target_ref: "refs/remotes/origin/master", target_commit_id: Sha1(350e04fe35433e6d2941dce5a1f53308f87058eb), push_remote: "origin" }), target_ref: Some(TargetRef { ref_name: FullName("refs/remotes/origin/master"), segment_index: NodeIndex(1), commits_ahead: 0 }), extra_target: None } paths=1
2026-01-22T08:54:23.111236Z  INFO handle:project_files_change:worktree_changes: crates\but-core\src\diff\worktree.rs:37: close time.busy=16.3ms time.idle=10.9µs event=ProjectFileChange(44510e02-5e5d-4836-a47d-fa498f65e243, .vs\gitdemo\FileContentIndex) repo=Repository { kind: WorkTree { is_linked: false }, git_dir: "C:\\Users\\zippr\\gitdemo\\.git", workdir: Some("C:\\Users\\zippr\\gitdemo") } workspace=Workspace(📕🏘️:0:gitbutler/workspace[🌳] <> ✓refs/remotes/origin/master on 350e04f) { id: 0, kind: Managed { ref_info: RefInfo { ref_name: FullName("refs/heads/gitbutler/workspace"), worktree: Some(Main) } }, stacks: [Stack(≡📙:8:sz-branch-1 on 350e04f {ec452a13a824aa95161ff7e2552}) { segments: [StackSegment(📙:8:sz-branch-1) { commits: [], commits_on_remote: [], commits_outside: None }], id: ec452a13-a802-4a0a-9516-10f0f07e2552 }], metadata: Some(Workspace { ref_info: RefInfo { created_at: "2023-01-31 14:55:57 +0000", updated_at: None }, stacks: [WorkspaceStack { id: ec452a13-a802-4a0a-9516-10f0f07e2552, branches: [WorkspaceStackBranch { ref_name: "refs/heads/sz-branch-1", archived: false }], workspacecommit_relation: Merged }], target_ref: "refs/remotes/origin/master", target_commit_id: Sha1(350e04fe35433e6d2941dce5a1f53308f87058eb), push_remote: "origin" }), target_ref: Some(TargetRef { ref_name: FullName("refs/remotes/origin/master"), segment_index: NodeIndex(1), commits_ahead: 0 }), extra_target: None } paths=1
2026-01-22T08:54:23.111497Z  INFO handle:project_files_change: crates\gitbutler-watcher\src\handler.rs:87: close time.busy=16.6ms time.idle=40.4µs event=ProjectFileChange(44510e02-5e5d-4836-a47d-fa498f65e243, .vs\gitdemo\FileContentIndex) repo=Repository { kind: WorkTree { is_linked: false }, git_dir: "C:\\Users\\zippr\\gitdemo\\.git", workdir: Some("C:\\Users\\zippr\\gitdemo") } workspace=Workspace(📕🏘️:0:gitbutler/workspace[🌳] <> ✓refs/remotes/origin/master on 350e04f) { id: 0, kind: Managed { ref_info: RefInfo { ref_name: FullName("refs/heads/gitbutler/workspace"), worktree: Some(Main) } }, stacks: [Stack(≡📙:8:sz-branch-1 on 350e04f {ec452a13a824aa95161ff7e2552}) { segments: [StackSegment(📙:8:sz-branch-1) { commits: [], commits_on_remote: [], commits_outside: None }], id: ec452a13-a802-4a0a-9516-10f0f07e2552 }], metadata: Some(Workspace { ref_info: RefInfo { created_at: "2023-01-31 14:55:57 +0000", updated_at: None }, stacks: [WorkspaceStack { id: ec452a13-a802-4a0a-9516-10f0f07e2552, branches: [WorkspaceStackBranch { ref_name: "refs/heads/sz-branch-1", archived: false }], workspacecommit_relation: Merged }], target_ref: "refs/remotes/origin/master", target_commit_id: Sha1(350e04fe35433e6d2941dce5a1f53308f87058eb), push_remote: "origin" }), target_ref: Some(TargetRef { ref_name: FullName("refs/remotes/origin/master"), segment_index: NodeIndex(1), commits_ahead: 0 }), extra_target: None } paths=1
2026-01-22T08:54:23.112549Z  INFO handle: crates\gitbutler-watcher\src\handler.rs:41: close time.busy=33.1ms time.idle=39.5µs event=ProjectFileChange(44510e02-5e5d-4836-a47d-fa498f65e243, .vs\gitdemo\FileContentIndex)
```

On my system, after Visual Studio Community is closed, no such errors occur anymore in the logs, and GitButler always reliably tracks file changes.

There is not a single `panic` entry in `tokio-console`. The following type of event occurs repeatedly, which might be relevant because it contains `gitbutler_watcher::watch_in_background`:
```
{"Spawn":{"id":9008023888461853,"at":{"secs_since_epoch":1769072070,"nanos_since_epoch":998199700},"fields":[{"name":"kind","value":"blocking"},{"name":"task.name","value":""},{"name":"task.id","value":132},{"name":"fn","value":"gitbutler_watcher::watch_in_background<&std::path::Path>::{{closure}}::{{closure}}"},{"name":"size.bytes","value":176}]}}
```

**Comment by Byron** [comment]
That's awesome, thanks, I think we are onto something here.

What I see is that it does pickup changes, but the diff fails so badly that it can't display anything anymore.
Maybe this is due to a file controlled by vscode that it can't open for reading, apparently `.vs\gitdemo\FileContentIndex` which probably isn't .gitignored.

The solution here would be to not fail if a file can't be diffed, but continue on a best-effort basis.

**Comment by zipproth** [comment]
Thanks, so it turns out to be that straightforward.

This was a demo repo, and I hadn't added the `.vs` directory to `.gitignore` (I was sharing my positive GitButler experience with a Windows user). After adding `.vs` to `.gitignore`, it works perfectly: File changes are now monitored and detected as expected.

So, a lot of troubleshooting, but in practice, this issue isn't relevant for typical workflows with proper ignores. Just to note, the original issue title focuses on Linux, where I personally don't encounter this problem – everything runs smoothly there.

**Comment by Byron** [comment]
That's so great to hear!

I will still look into this as we should not have this failure mode, which could arise for any amount of reasons with very confusing consequences.

So I am very much looking forward to hopefully solving this for good :).

**Comment by Byron** [comment]
This is now fixed, probably, with a fix in `gix`. If it still fails, I think Windows might come up with different error codes, as for now I constrain it to specific issues.

**Comment by peterramsay** [comment]
Just been able to reproduce this reliably when a binary file generated by my application was detected. As soon as I deleted said binary file and restarted GitButler, the problem was resolved.

**Comment by Byron** [comment]
Thanks!

Could I have logs for this? It would be good to know if this is still failing in `gix` or if it's something else.

Ideally, the logs would be from Nightly, and getting the logs is easier than ever.

<img width="421" height="546" alt="Image" src="https://github.com/user-attachments/assets/80d7faab-ac3c-4f9a-b702-0ccb8467c4af" />

**Comment by peterramsay** [comment]
Just tried to get you some logs in nightly and it appears the issue does not occur there!

**Comment by mfattakhov** [comment]
Hey! Was this a vs code/linux specific issue? I am getting it on mac os and zed. Mostly when agents from opencode edit files I have to refresh (cmd+r) to see changed files. The repo is always in focus, the workflow with gitbutler hasn't changed and some versions ago all was good.

**Comment by Byron** [comment]
@MFattakhov Could you start GitButler with this environment variable set? `GITBUTLER_WATCH_MODE=legacy`. 
If this works, you can set it permanently for now by editing the GitButler `settings.json` with:

```json
  "featureFlags": {
    "watch_mode": "legacy"
  },
```

**Comment by mfattakhov** [comment]
Unfortunately it didn't help 😔

**Comment by Byron** [comment]
This is great, as it means it's some other issue. 

<img width="538" height="514" alt="Image" src="https://github.com/user-attachments/assets/e4c9ee67-fcd9-42cf-a414-78965b3109bc" />

Can you check your logs and see if there is `WARN` or `ERROR` lines?

**Comment by mfattakhov** [comment]
I have those:
```
2026-02-25T04:13:49.738067Z  WARN stack_details: crates/but-workspace/src/changeset.rs:409: Stopping expensive changeset computation after 1s and 172 diffs computed (170.7152 diffs/s) ctx=Context { git_dir: "/Users/mfattakhov/delta-2/.git" } stack_id=Some(e5b6e2ea-1b5c-4c87-9e01-d50becf6db3b)
```

**Comment by Byron** [comment]
That is fascinating, as everything that can cause issues here either errors openly, or informs with warnings. Seeing nothing means everything is fine.
Is there a way for me to reproduce this, maybe by looking at the same repository?

**Comment by mfattakhov** [comment]
I will try to reinstall the gitbutler, maybe it will help. And try some open source repository, to see whether it is repo specific or global

**Comment by mfattakhov** [comment]
So reinstallation didn't help. I tried with the zed repo and it works there! So the problem is repo specific. You sure this warning is not related to the issue?
```
Stopping expensive changeset computation after 1s and 172 diffs computed
```

**Comment by Byron** [comment]
> So reinstallation didn't help. I tried with the zed repo and it works there! So the problem is repo specific. You sure this warning is not related to the issue?
> 
> ```
> Stopping expensive changeset computation after 1s and 172 diffs computed
> ```

Yes, I am certain.

And also I am completely lost on a fix for this as there is no observable error that would have led to the file watching not working.
Internally I have put rolling the gitignore-aware watcher on hold until we can reproduce it. Meantime, it only activates in WSL, or if it's explicitly configured via `settings.json`.

**Comment by mfattakhov** [comment]
After reinstallation there are some errors in the logs btw:
```
2026-02-26T07:50:52.138432Z ERROR crates/gitbutler-git/src/executor/tokio/mod.rs:79: Git invocation failed cmd=Command { std: cd "/Users/mfattakhov/delta" && env -u GITBUTLER_ASKPASS_PIPE -u GITBUTLER_ASKPASS_SECRET -u SSH_ASKPASS DISPLAY=":" GIT_SSH_COMMAND="'/Applications/GitButler.app/Contents/MacOS/gitbutler-git-setsid' ssh -o StrictHostKeyChecking=accept-new -o KbdInteractiveAuthentication=no" GIT_TERMINAL_PROMPT="0" LC_ALL="C" "git" "-c" "protocol.version=2" "--no-pager" "fetch" "--quiet" "--prune" "origin" "+refs/heads/*:refs/remotes/origin/*", kill_on_drop: true } stdout="" stderr="error: cannot lock ref 'refs/remotes/origin/PX-4013-order-details': is at f6706f49fc7a7e289f1fa6da16f2ad2951c41f91 but expected 447361589bc3ab9dc79b3714f1c0c7bd57f612b1\nwarning: The last gc run reported the following. Please correct the root cause\nand remove .git/gc.log\nAutomatic cleanup will not be performed until the file is removed.\n\nwarning: There are too many unreachable loose objects; run 'git prune' to remove them.\n\n"
2026-02-26T07:50:53.187014Z ERROR fetch_from_remotes: crates/but-api/src/legacy/virtual_branches.rs:306: error=backend error: git command exited with non-zero exit code 1: ["fetch", "--quiet", "--prune", "origin", "+refs/heads/*:refs/remotes/origin/*"]
2026-02-26T07:54:23.767800Z ERROR get_base_branch_data:get_base_branch_data: crates/gitbutler-branch-actions/src/base.rs:61: error=errors.projects.default_target.not_found
2026-02-26T07:54:23.820064Z ERROR changes_in_worktree: crates/but-db/src/handle.rs:33: error=database is locked
2026-02-26T07:54:23.820085Z ERROR changes_in_worktree: crates/but-api/src/legacy/diff.rs:29: error=database is locked
2026-02-26T07:54:25.518624Z ERROR set_base_branch:set_base_branch_with_perm:create_snapshot: crates/gitbutler-oplog/src/oplog.rs:149: error=errors.projects.default_target.not_found
```
and warnings are all about `Stopping expensive changeset computation after 1s and 18 diffs computed`

**Comment by Byron** [comment]
Thanks!

The errors (unfortunately) strike me as unrelated though.

**Comment by mfattakhov** [comment]
@Byron hi! looks like the last update fixed the thing, thx!

**Comment by Byron** [comment]
Great, then I think it really is related to the new file watcher.

**Comment by krlvi** [comment]
The Visual Studio Community failure reported here was fixed in https://github.com/gitbutlerapp/gitbutler/pull/11958 and shipped in `0.18.7`. We also fixed the later file-watcher regression discussed near the end of the thread in https://github.com/gitbutlerapp/gitbutler/pull/12589, shipped in `0.19.4`, and the reporter confirmed that update resolved it.

I’m closing this as fixed. The broader AppImage and WSL watcher edge cases are still tracked in #4713.
