### ISSUE TITLE
Secret Service: no result found error when opening GitButler

### ISSUE THREAD

**Issue by techfg** [gitbutlerapp/gitbutler#9519]
### Version

0.15.4

### Operating System

Linux

### Distribution Method

AppImage (Linux)

### Describe the issue

When opening GitButler, a toast in the lower right corner indicates `Secret Service: no result found`

When opening seahorse, there are no entries in any keyrings.

Prior to installing `gnome-keyring`, I was encountering the error `The name of org.freedesktop.secrets was not provided by any....` so installing it via `sudo apt install gnome-keyring` definitely changed behavior.

Related #9507 

### How to reproduce (Optional)

1. Open GitButler
2. Click "Log in or Sign up"
3. Choose Github and go through login process if not already logged in - receive the "You are successfully logged in!" page
4. Return to GitButler and all is connected as would be expected
5. Close GitButler
6. Open GitButler - this is where Secret Service: no result found is encountered

### Expected behavior (Optional)

GitButler is logged in to Github account.

### Relevant log output (Optional)

N/A

**Comment by techfg** [comment]
@Byron - One additional observation....when I click "Log in or Sign up", it launches my Windows default browser (currently Edge), likely because I have wslu installed.  I haven't reviewed the GB code to see how the flow works but possibly the interplay of O/Ss here is what might be causing an issue?  

EDITED: Unstalled wslu, went through login to GitHub process again, closed GB, opened GB, same `Secret Service: no result found` error and nothing in keyring.  Kind of what I expected given it's likely an auth code flow with a callback but worth a shot :(

**Comment by techfg** [comment]
> 1. What OS are you running?
> 
> I am running GitButler in an Ubuntu distrobox on Bluefin.
> 
> 2. Did you do anything besides `sudo apt install gnome-keyring`?
> 
> Nope, unless you count logging back into all the GitButler accounts. I might have restarted the distrobox, but unfortunately I'm not sure about that anymore.
> 
> 3. Do you see an entry for the secret that GB created and if so, where?
> 
> I hadn't actually checked, and I also know basically nothing about keychains etc., but here's (the relevant part of) what I see when I open seahorse within the Ubuntu distrobox:
> 
> <img width="1693" height="1209" alt="Image" src="https://github.com/user-attachments/assets/b1a8b2b4-4393-463f-a4e4-08c43e881c22" /> 

 _Originally posted by @jeyj0 in [#9507](https://github.com/gitbutlerapp/gitbutler/issues/9507#issuecomment-3106254797)_

@jeyj0 - Thanks for sharing!  I have restarted the distro but unfortunately, no difference.  Did you create the "Login" password keyring or did GitButler possibly create this when it added the secret?

@Byron - FWIW, I created a password keyring called "Login" just in case it was name specific but unfortunately, still not working.

Here's some log information I found:

```
2025-07-23T08:01:57.756863Z ERROR crates/gitbutler-tauri/src/secret.rs:9: error=Error(Couldn't access platform secure storage: Secret Service: no result found

Caused by:
    Secret Service: no result found)
[2025-07-23][08:01:57][webview:q@tauri://localhost/_app/immutable/entry/app.BgxX5jHt.js:4:849][ERROR] [object Object]
```

**Comment by Byron** [comment]
> [@jeyj0](https://github.com/jeyj0) - Thanks for sharing! I have restarted the distro but unfortunately, no difference. Did you create the "Login" password keyring or did GitButler possibly create this when it added the secret?

GitButler does not create keychains for sure, but I am certain that the underlying crate has the notion of a default keychain where new secrets go.

It looks like the difference is the lack of 'official' login keychain, and the name along doesn't seem to cut it.
There seems to be a way to designate default keychains, but [it might all be garbage](https://chatgpt.com/share/6880a5ca-668c-800a-b240-a882bfa3b2c1) as well.

**Comment by jeyj0** [comment]
> @jeyj0 - Thanks for sharing! I have restarted the distro but unfortunately, no difference. Did you create the "Login" password keyring or did GitButler possibly create this when it added the secret?

I had never opened seahorse or done anything manually with keyrings before. It just worked™

**Comment by techfg** [comment]
> > [@jeyj0](https://github.com/jeyj0) - Thanks for sharing! I have restarted the distro but unfortunately, no difference. Did you create the "Login" password keyring or did GitButler possibly create this when it added the secret?
> 
> GitButler does not create keychains for sure, but I am certain that the underlying crate has the notion of a default keychain where new secrets go.
> 
> It looks like the difference is the lack of 'official' login keychain, and the name along doesn't seem to cut it. There seems to be a way to designate default keychains, but [it might all be garbage](https://chatgpt.com/share/6880a5ca-668c-800a-b240-a882bfa3b2c1) as well.

Setting the default is the "key" (pun intended) 😄  The command `gsettings set org.gnome.crypto.keyring default 'Login'` from your link didn't work (error: `No such schema “org.gnome.crypto.keyring”`) but opening seahorse, choosing the "Login" keyring, right-clicking and choosing "Set Default" does the same.  Assuming there's a way to do this via CLI as well.

Once I did this, opened GitButler, logged in to GitHub, I was prompted for my keyring password and after entering, I can now see the GB secret.  I then closed/open DB and it still thinks I'm logged in so that problem appears to be solved, thanks everyone!

**Comment by Byron** [comment]
That's so great to hear!

Then I will close this issue by picking up on the error message, and show a hint to suggest doing what you did.

**Comment by techfg** [comment]
Sounds great!  One other thought is that I suspect that when "writing" the secret, it might be failing at some level and going undetected currently?  If so, possibly there's a way to surface a message at that point but at the very least, on "read" having more info should be able to steer users in the right direction.

**Comment by Byron** [comment]
Indeed, it would be great if this error would show up everywhere. Unfortunately, it seems to be the underlying library which doesn't provide one as we never swallow any.

https://github.com/gitbutlerapp/gitbutler/blob/c7298758d4c1188644b62194a358c513f660121d/crates/gitbutler-secret/src/secret.rs#L28-L33

Here there are multiple places where it could and probably should fail, but it doesn't seem to be happening.

Ultimately, I have a feeling that for much better keychain support, we'd have to contribute fixes to the underlying library or maintain a variant of it ourselves.

**Comment by techfg** [comment]
Interesting....disappointing that nothing is being surfaced by the underlying library - possibly it's just making an assumption that there is always a default but even that seems odd.  

At the very least, the "read error" on startup along with added help info will point users in the right direction short of any potential future improvements to the GB/keychain interop.

Thanks again @Byron!

**Comment by shmillery** [comment]
I am experiencing this as well after upgrading a WSL2 AppImage install from 0.15.2 -> 0.15.5. Reverting back to 0.15.2 does not show this error. 

```
2025-07-25T17:52:10.463801Z ERROR crates/gitbutler-tauri/src/secret.rs:9: error=Error(errors.secret.missing_login_keychain

Caused by:
    0: Couldn't access platform secure storage: Secret Service: no result found
    1: Secret Service: no result found)
```

As far as I know WSL2 does not have a secret keychain running by default, is this a new requirement to install and configure one?

**Comment by Byron** [comment]
Indeed, the secret store was switched to a permanent one - previously it would loose everything after a reboot.

Now you should see this instead of that error though, making clear what needs to be done to make the error go away.

<img width="917" height="1084" alt="Screenshot 2025-07-23 at 16 22 34" src="https://github.com/user-attachments/assets/cde1b218-8f92-41e4-a17c-3c2ec7b3b8e1" />

**Comment by shmillery** [comment]
Thanks @Byron, just wanted to confirm that was the correct path for WSL2 as well. after installing `seahorse` and configuring a default password store the issue is resolved.
